### ISSUE TITLE
Replace the Neo4j driver

### ISSUE THREAD

**Issue by berteltorp** [ulobby/NeoEloquent#22]
The package currently uses the [everyman/neo4jphp](https://github.com/jadell/neo4jphp)-driver and the development of that  stalled around 2014.

Since then neo4j has evolved a lot (ex. introduced bolt a more efficient protocol and cluster support with bolt+routing).

The driver is implemented in [NeoEloquent/blob/master/src/Connection.php](https://github.com/ulobby/NeoEloquent/blob/master/src/Connection.php)

### Replacement candidates:

|   |  Name | Routing support |
|---|---|---|
|  1 |  [laudis/neo4j-php-client](https://github.com/laudis-technologies/neo4j-php-client)  |  ⏳ Planned  |
|  2 |  [stefanak-michal/bolt](https://github.com/stefanak-michal/Bolt) | 🛑 No  |
| 3  |  [plumtreesystems/neo4j-bolt](https://github.com/PlumTreeSystems/neo4j-bolt-php) | 🛑  No   |

**Comment by berteltorp** [comment]
Looks like 2. does partially (if you connect to the leader) https://github.com/stefanak-michal/Bolt/issues/42

**Comment by SimonThordal** [comment]
There is additionally this one which might support it at some point: https://github.com/PlumTreeSystems/neo4j-bolt-php

**Comment by berteltorp** [comment]
Maybe it's premature for us to work on a new driver before we have a candidate with cluster-support? 🤔

**Comment by berteltorp** [comment]
3. has no current plans for routing: https://github.com/PlumTreeSystems/neo4j-bolt-php/issues/6

**Comment by GinoPane** [comment]
It looks like `laudis/neo4j-php-client` has routing support now

**Comment by idevin** [comment]
> It looks like `laudis/neo4j-php-client` has routing support now

YES!

**Comment by berteltorp** [comment]
We decided on 1. - it's implemented in v.9
