### ISSUE TITLE
query Exception during migrate

### ISSUE THREAD

**Issue by cedvict** [ulobby/NeoEloquent#26]
Hi Guys
I have some error occurred during migrate
Can someone help me?
![image](https://user-images.githubusercontent.com/8941921/106651009-def30b00-6593-11eb-9ba0-d81fd6103693.png)
Thanks in advance

**Comment by harris21** [comment]
Hello @cedvict,

like mention in https://github.com/ulobby/NeoEloquent/issues/27#issuecomment-771993415 , would you please provide us some more information?
In addition to the ones mentioned in the provided link, could you also show us what's your migration like?

Thanks!

**Comment by cedvict** [comment]
> Hello @cedvict,
> 
> like mention in [#27 (comment)](https://github.com/ulobby/NeoEloquent/issues/27#issuecomment-771993415) , would you please provide us some more information?
> In addition to the ones mentioned in the provided link, could you also show us what's your migration like?
> 
> Thanks!

Hello @harris21 
The migration is for conventionnal sql dbms. I try to make migration with neo4j

**Comment by berteltorp** [comment]
@cedvict Are you running `php artisan neo4j:migrate` to run a mysql migration? 🤔

**Comment by cedvict** [comment]
No. I have executed neo4j:migrate:reset to get this. At the same when to open laravel in browser

**Comment by harris21** [comment]
Hey @cedvict, would you please share the exact steps that you followed so we can try and reproduce your issue?
Screenshot of your terminal would help as well!

**Comment by cedvict** [comment]
Hi @harris21 

After install ulobby/NeoEloquent I try to make migration (php artisan neo4j:make:migration user) and I get this result
![image](https://user-images.githubusercontent.com/8941921/106860269-6a6bb980-66c4-11eb-8d1a-87c588bd4995.png)
Also I try to reset migration (php artisan neo4j:migrate:reset) and I get this result
![image](https://user-images.githubusercontent.com/8941921/106860517-cd5d5080-66c4-11eb-88b8-037e289ef374.png)

My composer.json file
![image](https://user-images.githubusercontent.com/8941921/106860645-f67de100-66c4-11eb-8f62-9df019b880f5.png)

Neo4j database setting
![image](https://user-images.githubusercontent.com/8941921/106860744-16ada000-66c5-11eb-9574-ceee4066a8d3.png)

**Comment by cedvict** [comment]
Mistake
![image](https://user-images.githubusercontent.com/8941921/106861084-90de2480-66c5-11eb-8f4e-71c0d0fe0ac2.png)

**Comment by raavus-funkmaster** [comment]
Are other commands or functions working? What about your neo4j dockerfile? If you are running 4.0+ then neoeloquent is going to be attempting to send requests to endpoints that no longer exist and you'll get this 404 response.

**Comment by SimonThordal** [comment]
Hi @cedvict, we've made a fix to `php artisan neo4j:make:migration` that might solve at least one of your problems.
Additionally could you check that your Neo4j version is on 3.5 and not 4.0? NeoEloquent currently doesn't support 4.0+.

**Comment by cedvict** [comment]
Thanks 👍

**Comment by berteltorp** [comment]
Closing as fixed.
