### ISSUE TITLE
Error after execution of neo4j:make:migration

### ISSUE THREAD

**Issue by cedvict** [ulobby/NeoEloquent#27]
Hi Guys

When I try to execute php artisan neo4j:make:migration, I get this
![image](https://user-images.githubusercontent.com/8941921/106652036-347be780-6595-11eb-8af0-deccb4c0e6c6.png)

Can someone help to resolve it ? Please

**Comment by harris21** [comment]
Hello @cedvict,

could you please give us some more information:
1. What's your Laravel version?
2. Which version of NeoEloquent do you use?
3. which PHP version?
4. What's your OS?

I just tried generating a new migration using the same command and it worked as expected.

Thanks!

**Comment by cedvict** [comment]
> Hello @cedvict,
> 
> could you please give us some more information:
> 
> 1. What's your Laravel version?
> 2. Which version of NeoEloquent do you use?
> 3. which PHP version?
> 4. What's your OS?
> 
> I just tried generating a new migration using the same command and it worked as expected.
> 
> Thanks!

Hello @harris21

Thanks for you reply

1. Laravel v8
2. ulobby/NeoEloquent v8.0
3. Php v7.4
4. OS ubuntu 20.04

**Comment by berteltorp** [comment]
Thanks for the tip @raavus-funkmaster ! 

@cedvict The fix will be released once reviewed 😄
