### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by dmp593** [ulobby/NeoEloquent#4]
Hello, I like your project.
When do you plan to migrate to Laravel 6?
Thanks.

**Comment by SimonThordal** [comment]
We're still in Alpha, so it's not right around the corner. We will also need it to run 6.0 in the spring though, so it will happen.

**Comment by v16Studios** [comment]
Looks like Laravel 6 is now supported 🙂 https://github.com/ulobby/NeoEloquent/releases

**Comment by berteltorp** [comment]
That is correct - go ahead and update! 😄
