### ISSUE TITLE
Tag for laravel 5.8 support

### ISSUE THREAD

**Issue by senyahnoj** [ulobby/NeoEloquent#5]
Thanks for forking this project and bringing it up to laravel 5.8.

The latest tag in this repository is 1.4.7 which still depends on laravel 5.6. Are you in a position to be able to tag a more recent version with laravel 5.8?

**Comment by berteltorp** [comment]
Sure - i've just tagged a release for you [🔖 1.4.8](https://github.com/ulobby/NeoEloquent/releases/tag/v.1.4.8)

**Comment by senyahnoj** [comment]
Thanks!

**Comment by senyahnoj** [comment]
Don't seem to be able to pick this up on packagist - https://packagist.org/packages/ulobby/neoeloquent - latest tag here is still v1.4.7 - is there something blocking the tag coming through?

**Comment by senyahnoj** [comment]
I think the problem might have something to do with the tag having a dot after the v and before the 1.

* v1.4.7
* v.1.4.8

My composer "requires" section has

"ulobby/neoeloquent": "^1.4.0"

Compose update will find tags prefixed like 1.4.8 or v1.4.8 but I think the composer version constraint system can't handle the v.1.4.8 - https://getcomposer.org/doc/articles/versions.md

**Comment by berteltorp** [comment]
My bad - updated 😄

**Comment by senyahnoj** [comment]
👍
