### ISSUE TITLE
Neo4j version 4 support

### ISSUE THREAD

**Issue by senyahnoj** [ulobby/NeoEloquent#8]
Are you planning to support Neo4j 4.0.0?

I tried this library with a neo4j 4.0.0 and it wasn't compatible. NeoEloquent is using heydavid713/neo4jphp for connectivity but I can see that there have been some changes to the cypher transaction API https://neo4j.com/docs/http-api/4.0/actions/

Thank you for your time

**Comment by SimonThordal** [comment]
Hopefully at some point, but it's not something that's being worked on at the moment.
